[package]
name = "facestuff-rust"
version = "0.1.0"
authors = ["Me"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = {version = "0.46", features = ["contrib"]}
clap = "2.33"
